#!/bin/bash
### Upgrade Deb8 to Deb9

Check 3rd-party
aptitude search '~o'

##
apt-get remove fai2ban -y
###
apt-get update
apt-get upgrade -y --force=yes
apt-get dist-upgrade -y --force=yes
dpkg -C
apt-mark showhold

## Backup Repository
cp /etc/apt/sources.list /etc/apt/sources.list_backup

### Change Repository
sed -i 's/jessie/stretch/g' /etc/apt/sources.list

## Upgrade to 9
apt-get update
apt list --upgradable
apt-get upgrade -y
apt-get dist-upgrade -y
aptitude search '~o'

# Install Fail2ban
apt-get install fail2ban -y
##
echo "Upgrade Finish"
reboot
