#!/bin/bash

############################
### Upgrade Deb8 to Deb9 ###
############################

# Check Git installation
if ! hash git 2>/dev/null; then sudo apt-get install --yes git ; fi

##Check 3rd-party
aptitude search '~o';

##
apt-get remove fail2ban -y;
apt-get purge fail2ban -y;
apt-get autoremove -y;

echo -e "\nFail2ban wird removed\n";
###
echo -e "\nUpgrade Debian 8\n";
apt-get update;
apt-get upgrade -y --force-yes;
apt-get dist-upgrade -y --force-yes;
dpkg -C;
apt-mark showhold;

## Backup Repository
echo -e "\nSourceliste wird kopiert\n";
cp /etc/apt/sources.list /etc/apt/sources.list_backup;

### Change Repository
sed -i 's/jessie/stretch/g' /etc/apt/sources.list;
echo -e "\nNeue Sourceliste angelegt\n";


## Upgrade to 9
echo -e "\nUpgrade to Debian 9\n";
apt-get update;
apt list --upgradable;
apt-get upgrade -y;
apt-get dist-upgrade -y;
aptitude search '~o';

# Install Fail2ban
echo -e "\Install Fail2ban\n";
apt-get install fail2ban -y;
##
echo "Upgrade Finish";
reboot
