#!/bin/bash

#########################################
### Sync old mail accounts 2 new postdir#
#########################################

## Struktur ##
## old $base /var/mail/virtual/DOMAIN/USER/FOLDER
## new $base /var/vmail/DOMAIN/USER/Maildir/

#Variablen
domain=xcoorp.net
elitelog=account_${domain}.txt



## Schleife

#for file in *;
#do
#  find "$file" -type f -not -name ".*" | grep .exe$ | grep RARBG | while read file
#  do
#        echo $file gefunden. - REMOVE | tee -a remove_txt.log >> $elitelog
#        rm $file
#  done
#done

cd $domain

for file in *;
do
  find "$file" -maxdepth 1 -type d | while read file
  do
        pfad=$(readlink -f "$file")
        echo $file  >> $elitelog
       # Anweisung rm -r $file
  done
done

cd ..
